import type { Product, Order } from '@/types'

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-1',
    name_fr: 'Miel de Thym',
    name_ar: 'عسل الزعتر',
    description_fr: 'Un miel rare et aromatique, récolté dans les champs de thym sauvage du Rif. Notes florales et herbacées, idéal contre les infections.',
    description_ar: 'عسل نادر وعطري، يُجمع من حقول الزعتر البري في الريف. له نكهة زهرية وعشبية، مثالي لمكافحة العدوى.',
    price: 120,
    image_url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&q=80',
    category: 'thyme',
    weight: '500g – 1kg',
    origin: 'Rif, Maroc',
    stock: 45,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    name_fr: 'Miel de Sidr',
    name_ar: 'عسل السدر',
    description_fr: 'Le roi des miels marocains. Récolté une seule fois par an dans les forêts de jujubier du Souss. Texture crémeuse, richesse incomparable.',
    description_ar: 'ملك الأعسال المغربية. يُجمع مرة واحدة في السنة من غابات السدر بسوس. قوام كريمي وغنى لا مثيل له.',
    price: 250,
    image_url: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=400&q=80',
    category: 'sidr',
    weight: '250g – 500g',
    origin: 'Souss-Massa, Maroc',
    stock: 20,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    name_fr: 'Miel de Montagne',
    name_ar: 'عسل الجبل',
    description_fr: 'Récolté à plus de 2000m d\'altitude dans le Haut Atlas. Riche en polyphénols, ce miel polyfloral aux mille vertus est le préféré des connaisseurs.',
    description_ar: 'يُجمع على ارتفاع يزيد عن 2000 متر في الأطلس الكبير. غني بالبوليفينول، هذا العسل متعدد الأزهار المفضل لدى العارفين.',
    price: 150,
    image_url: 'https://images.unsplash.com/photo-1471943038711-71d2e49d4ce3?w=400&q=80',
    category: 'mountain',
    weight: '500g – 1kg – 2kg',
    origin: 'Haut Atlas, Maroc',
    stock: 60,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    name_fr: 'Miel de Fleurs Sauvages',
    name_ar: 'عسل الأزهار البرية',
    description_fr: 'Un bouquet de saveurs issu de la biodiversité marocaine. Ce miel multifloral capture l\'essence des prairies de printemps.',
    description_ar: 'باقة من النكهات مستوحاة من التنوع البيولوجي المغربي. يلتقط هذا العسل متعدد الأزهار جوهر مروج الربيع.',
    price: 90,
    image_url: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    category: 'wildflower',
    weight: '500g – 1kg',
    origin: 'Moyen Atlas, Maroc',
    stock: 80,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    name_fr: 'Miel d\'Argan',
    name_ar: 'عسل الأركان',
    description_fr: 'Une rareté absolue. Les abeilles butinent les fleurs d\'arganier, un arbre endémique du Maroc. Saveur unique légèrement boisée et fruitée.',
    description_ar: 'ندرة مطلقة. النحل يتغذى على أزهار الأركان، وهي شجرة مستوطنة في المغرب. نكهة فريدة خشبية وفاكهية قليلاً.',
    price: 300,
    image_url: 'https://images.unsplash.com/photo-1601055283742-8b27e81b5553?w=400&q=80',
    category: 'argan',
    weight: '250g – 500g',
    origin: 'Sous-Massa, Maroc',
    stock: 15,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    name_fr: 'Miel d\'Euphorbe',
    name_ar: 'عسل الدافلة',
    description_fr: 'Extrait des fleurs d\'euphorbe résineuse du désert marocain. Ce miel blanc est renommé pour ses propriétés apaisantes des voies respiratoires.',
    description_ar: 'مستخرج من أزهار الدافلة في الصحراء المغربية. هذا العسل الأبيض مشهور بخصائصه المهدئة للجهاز التنفسي.',
    price: 200,
    image_url: 'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=400&q=80',
    category: 'euphorbe',
    weight: '500g',
    origin: 'Sahara, Maroc',
    stock: 25,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEMO_ORDERS: Order[] = [
  {
    id: 'demo-order-1',
    order_number: 1,
    customer_name: 'Fatima Zahra Benali',
    phone: '+212661234567',
    city: 'Casablanca',
    address: '45 Rue Mohammed V',
    items: [
      { product_id: 'demo-1', product_name_fr: 'Miel de Thym', product_name_ar: 'عسل الزعتر', quantity: 2, unit_price: 120 },
      { product_id: 'demo-2', product_name_fr: 'Miel de Sidr', product_name_ar: 'عسل السدر', quantity: 1, unit_price: 250 },
    ],
    subtotal: 490,
    total: 490,
    status: 'confirmed',
    notes: 'Emballage cadeau svp',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-order-2',
    order_number: 2,
    customer_name: 'Youssef El Mansouri',
    phone: '+212671234567',
    city: 'Marrakech',
    address: null,
    items: [
      { product_id: 'demo-3', product_name_fr: 'Miel de Montagne', product_name_ar: 'عسل الجبل', quantity: 3, unit_price: 150 },
    ],
    subtotal: 450,
    total: 450,
    status: 'pending',
    notes: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
]
